apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mar-12-beta-09
  region: us-west-2
  version: "1.32"

iam:
  withOIDC: true

managedNodeGroups:
  - name: managed-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
