apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mar-10-beta-02
  region: us-west-2

iam:
  withOIDC: true

managedNodeGroups:
  - name: managed-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20

#nodeGroups:
#  - name: ng-1
#    instanceType: t3.medium
#    desiredCapacity: 2
#    minSize: 1
#    maxSize: 3
