AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EKS cluster using a custom Lambda function with a unique name.

Resources:
  ControlPlane:
    Type: Custom::EksCluster
    Properties:
      ServiceToken: !GetAtt CustomEKSFunction.Arn
      RoleArn: !GetAtt ServiceRole.Arn

  CustomEKSFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CustomEKSFunction'
      Handler: index.handler
      Runtime: python3.9
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EKSClusterCreationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - eks:*
                  - cloudformation:DescribeStacks
                Resource: '*'
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt ServiceRole.Arn
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'  # Allow access to all log groups

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt CustomEKSFunction.Arn
      Principal: 'cloudformation.amazonaws.com'
    DependsOn:
      - CustomEKSFunction  # Explicit dependency on CustomEKSFunction

Outputs:
  ClusterArn:
    Description: ARN of the created EKS cluster
    Value: !GetAtt ControlPlane.PhysicalResourceId
  Arn:
    Description: ARN of the created EKS cluster
    Value: !GetAtt ControlPlane.PhysicalResourceId
  ClusterName:
    Description: Name of the created EKS cluster
    Value: !GetAtt ControlPlane.ClusterName
